W1:
  type: spout
  sink: False
  input: tweets.csv
  children: [W2]
  
W2:
  type: bolt
  sink: False
  function_type: filter
  function: "lambda tweet: len(tweet[7]) > 10"
  parents: [W1]
  children: [W3]

W3:
  type: bolt
  sink: True
  function_type: transform
  function: "lambda tweet: tweet[7] + '123'"
  parents: [W2]
  output: modified_tweets.txt