W1:
  type: spout
  sink: False
  input: modified_house_data.csv
  children: [W2]

W2: 
  type: bolt
  sink: False
  function_type: filter
  function: "lambda house: int(house[0]) > 80000"
  parents: [W1]
  children: [W3]

W3:
  type: bolt
  sink: True
  function_type: transform
  function: "lambda house: house[0] + 'hello world'"
  parents: [W2]
  output: modified_house_data.txt