W1:
  type: spout
  sink: False
  input: tweets-5k.csv
  children: [W2, W3]

W2:
  type: bolt
  sink: False
  function_type: filter
  function: "lambda tweet: 'Mon' in tweet[2]"
  parents: [W1]
  children: [W4]

W3: 
  type: bolt
  sink: False
  function_type: filter
  function: "lambda tweet: '@mileycyrus' in tweet[5]"
  parents: [W1]
  children: [W4]

W4:
  type: bolt
  sink: False
  function_type: transform
  function: "lambda tweet: 1"
  parents: [W2, W3]
  children: [W5]

W5:
  type: bolt
  sink: True
  function_type: aggregate
  function: "operator.add"
  parents: [W4]
  output: tweets-5k-output.txt